name: Test

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  minimal-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv venv
          uv pip install -e ".[dev]"

      - name: Check installation
        run: |
          uv run python --version
          uv run python -c "import yaml; print('✅ PyYAML imported')"
          uv run python -c "import pytest; print('✅ pytest imported')"

      - name: Test basic functionality
        run: |
          echo "Testing basic conversion..."
          echo "vmess://eyJhZGQiOiJleGFtcGxlLmNvbSIsImFpZCI6IjAiLCJpZCI6InRlc3QiLCJuZXQiOiJ0Y3AiLCJwb3J0IjoiNDQzIiwicHMiOiJUZXN0Iiwic2N5IjoiYXV0byIsInRscyI6InRscyIsInYiOiIyIn0=" | uv run python src/jms_to_clash.py > test_output.yaml
          head -5 test_output.yaml
          echo "✅ Basic conversion works"

      - name: Run single test
        run: |
          uv run pytest test_jms_to_clash.py::TestProxyDecoders::test_decode_vmess -v

      - name: Check code style
        run: |
          uv run black --check --diff src/
          echo "✅ Black formatting check passed"

      - name: Check linting
        run: |
          uv run ruff check src/
          echo "✅ Ruff linting check passed"
